---
abstract: 'Serviço de cálculo de preços e prazos de entrega de encomendas (Brazilian Postal shipping cost and delivery time)'
author:
  - '-2014, Breno G. de Oliveira, Blabos de Blebe.'
  - 'Breno G. de Oliveira <garu@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
  Module::Install: 0
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.10'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Correios-PrecoPrazo
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Const::Fast: 0.012
  LWP::UserAgent: 0
  URI: 0
  URI::Escape: 0
  perl: 5.8.8
resources:
  bugtracker: https://github.com/garu/WWW-Correios-PrecoPrazo/issues
  license: http://www.perlfoundation.org/artistic_license_1_0
  repository: https://github.com/garu/WWW-Correios-PrecoPrazo.git
version: '0.3'
